stages:
  - build
build:
  stage: build
  script:
    - docker build -t registry.denistv777.ru/open/myheat-prometheus-exporter:latest --target=app-image -f Dockerfile .
    - docker push registry.denistv777.ru/open/myheat-prometheus-exporter:latest
