default:
  image: registry.denistv777.ru/docker:24.0.5
  services:
    - name: docker:24.0.5-dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"
stages:
  - build

build:
  stage: build
  script:
    - docker build -t registry.denistv777.ru/open/myheat-prometheus-exporter --target=app-image -f Dockerfile --label "version=`git describe --tags`" .
    - docker push registry.denistv777.ru/open/myheat-prometheus-exporter

